export const projects = [
    {
        slug: "rua-tours",
        title: "RUA Tours",
        description: "A full-featured tourism management platform for a premium Sri Lankan tour operator.",
        client: "RUA Tours Sri Lanka",
        date: "2025",
        role: "Full Stack Developer",
        overview: "A comprehensive tourism management platform built for a premium Sri Lankan tour operator. Features destination browsing, tour package management, booking systems, and an admin dashboard for managing tours, bookings, and customers.",
        features: [
            "Comprehensive tour package listing & itinerary management",
            "Seamless online booking & reservation system",
            "Admin dashboard for efficient tour & customer management",
            "Integrated travel blog system for destination insights",
            "Dynamic showcase of local activities and things to do",
            "Customizable travel itineraries with custom inquiry workflows",
        ],
        tech: ["PHP", "Laravel", "React.js", "JavaScript", "Tailwind CSS", "Sanity"],
        link: "https://ruatourssl.com/",
        image: "/rua.png",
        images: ["/rua.png"],
    },
    {
        slug: "noots",
        title: "Noots",
        description: "Dynamic music-centric social media platform integrated with Spotify, users to interact with music content.",
        client: "University Group Project",
        date: "2025",
        role: "Full Stack Developer",
        overview: "A music-centric social media platform integrating deeply with the Spotify API, allowing users to share, discover, and interact with music content through a beautifully crafted Flutter mobile app.",
        features: [
            "OAuth-based Spotify integration with real-time media controls",
            "Embedded media player with visual playback and track info",
            "Dynamic music-tied post system with comments, likes, and sharing",
            "Personalized feed system driven by social graph, location, and metadata",
            "Comprehensive user profiles with algorithmic follow suggestions",
            "Spectrum tracking system to map and analyze user listening patterns",
            "Subreddit-style Fanbases for community-driven music discovery",
            "Integrated real-time messaging",
        ],
        tech: ["NestJS", "Node.js", "Flutter", "Spotify API", "MongoDB"],
        frontendRepo: "https://github.com/Take-Noots/frontend.git",
        backendRepo: "https://github.com/Take-Noots/backend-nestjs.git",
        image: "/noot.png",
        images: ["/noot.png"],
    },
    {
        slug: "musicia",
        title: "Musicia",
        description: "Innovative web platform tailored for event planners, performers, and service providers across Sri Lanka.",
        client: "University Group Project",
        date: "2024",
        role: "Full Stack Developer",
        overview: "Musicia is a PHP MVC-based web application revolutionizing Sri Lanka's music event ecosystem by creating a centralized platform that connects event planners, performers, service providers, and audiences while solving fragmented communication and inefficient ticketing challenges.",
        features: [
            "Multi-Role Dashboards for Planners, Ticket Holders, Collaborators, & Admins",
            "End-to-End Event Management & Real-Time Profit Analytics",
            "Digital QR Code Ticket Generation with Automated Email Delivery",
            "Centralized Communication Hub & Real-Time Notification Center",
            "Integrated Interactive Event Calendar for Scheduling & Discovery",
            "Performer and Service Provider Profile Management System",
            "System-Wide Analytics & Comprehensive Event Reporting",
            "Secure Authentication & Platform Moderation Tools",
        ],
        tech: ["PHP", "HTML", "CSS", "JavaScript", "MVC", "MySQL"],
        repo: "https://github.com/Sachith-AB/Music-Event-Management-System.git",
        image: "/musicia.png",
        images: ["/musicia_page.jpg"],
    },
    {
        slug: "slice-of-sweet",
        title: "Slice-of-Sweet",
        description: "Online cake ordering system designed for special occasions with a smooth ordering and customisation flow.",
        client: "Academic Project",
        date: "2024",
        role: "Full Stack Developer",
        overview: "A comprehensive full-stack web application designed for ordering custom cakes and cupcakes online. It bridge the gap between customers and special occasions with a seamless ordering flow, from browsing a categorized menu to designing personalized creations using an interactive custom cake builder with dynamic pricing.",
        features: [
            "Interactive Custom Cake Builder with real-time previews and dynamic pricing",
            "Browse menu with detailed descriptions for Bento Cakes, Cupcake Packs, and Premium Cakes",
            "Secure and streamlined multi-step checkout with multiple pickup and payment options",
            "Comprehensive Admin Dashboard for managing products, orders, and user information",
            "JWT-based secure authentication for registered customer and admin sessions",
            "Engaging Homepage with auto-playing video showcase and interactive carousels",
            "Fully mobile-responsive interface for a seamless ordering experience on any device",
        ],
        tech: ["React.js", "Material-UI", "Node.js", "Express.js", "MongoDB", "JWT"],
        link: "https://slice-of-sweet.vercel.app/",
        image: "/cake kade.png",
        images: ["/cake kade.png"],
    },
    {
        slug: "movie-recommendation-system",
        title: "Movie Recommendation System",
        description: "Content-based recommendation system using NLP to suggest top 10 similar movies based on user input.",
        client: "Personal Project",
        date: "2025",
        role: "ML Engineer",
        overview: "This project is a content-based movie recommendation system. It uses natural language processing and machine learning techniques to suggest movies similar to a user's favorite. The system analyzes movie data such as genres, keywords, tagline, cast, and director to calculate similarity scores between movies.",
        features: [
            "Content-Based Filtering",
            "TF-IDF Vectorization",
            "Cosine Similarity",
            "Fuzzy String Matching",
            "Top-10 Recommendations",
            "Interactive Command-Line Interface",

        ],
        tech: ["Python", "Pandas", "NumPy", "Scikit-learn"],
        repo: "https://github.com/nethmi02/Movies-recommendation.git",
        image: "/movie.png",
        images: ["/movie.png"],
    },
    {
        slug: "meme-virality-predictor",
        title: "Meme Virality Predictor",
        description: "Interactive web application leveraging data analysis to predict the potential virality of memes.",
        client: "Personal Project",
        date: "2025",
        role: "Data Scientist & Developer",
        overview: "A data-driven web app that predicts meme virality potential. Users upload meme content  and receive a virality score generated through text and emoji feature analysis with a fast Streamlit UI.",
        features: [
            "Emoji and text feature extraction from memes",
            "Virality score prediction model",
            "Streamlit-based interactive web UI",
            "JSON-driven dataset integration",
            "Visual output with score breakdown",
        ],
        tech: ["Python", "Streamlit", "JSON"],
        repo: "https://github.com/nethmi02/Meme-Virality-Predictor.git",
        image: "/meme.png",
        images: ["/meme.png"],
    },
    {
        slug: "shards-of-dawn",
        title: "Shards of Dawn",
        description: "A 2D multiplayer platformer telling the story of four bearers of light working together to restore a shattered realm.",
        client: "University Game Project",
        date: "2025",
        role: "Game Developer",
        overview: "A 2D multiplayer platformer game where four bearers of ancient light cooperate across intricate levels to restore a shattered realm, featuring unique character abilities, cooperative puzzles, and enemy AI.",
        features: [
            "4-player cooperative multiplayer gameplay",
            "Unique abilities per character class",
            "Custom enemy AI and boss mechanics",
            "Rich narrative with cutscene support",
            "Custom physics and animation systems in Unity",
        ],
        tech: ["Unity", "C#"],
        repo: "https://github.com/desynkd/shards-of-dawn.git",
        image: "/game.png",
        images: ["/game.png"],
    },
    {
        slug: "finance-tracker",
        title: "Finance Tracker",
        description: "Sophisticated full-stack platform for seamless personal financial management and data-driven insights.",
        client: "Personal Project",
        date: "2026-present",
        role: "Full Stack Developer",
        overview: "A premium personal finance management application that empowers users to track, analyze, and manage their financial health. The platform integrates secure authentication with real-time data visualization and budgeting tools to promote financial discipline and transparency.",
        features: [
            "Enterprise-grade authentication and session management with Clerk",
            "Smart expense recording system with detailed categorization and metadata",
            "Interactive financial insights and spending trends with Recharts",
            "Dynamic budgeting tools to set monthly goals and monitor progress",
            "High-fidelity responsive UI with fluid animations using Framer Motion",
            "Automated financial data portability via built-in CSV export features",
        ],
        tech: ["React", "Tailwind CSS", "NestJS", "TypeScript", "Clerk", "Prisma", "Supabase", "TanStack Query", "Recharts"],
        frontendRepo: "https://github.com/FinPulse-Finance-Tracker/finance-tracker-frontend.git",
        backendRepo: "https://github.com/FinPulse-Finance-Tracker/finance-tracker-backend.git",
        image: "/finance.png",
        images: ["/finance.png"],
    }
];
